name: LFS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up LFS
      run: git lfs install

    - name: Set LFS URL
      run: echo "LFS_URL=${{ secrets.LFS_URL }}" >> $GITHUB_ENV

    - name: Pull LFS objects
      run: git lfs pull
